// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Admin struct {
	UserID    string       `json:"user_id"`
	CompanyID string       `json:"company_id"`
	DateAdded sql.NullTime `json:"date_added"`
}

type Company struct {
	CompanyID   string         `json:"company_id"`
	CompanyName string         `json:"company_name"`
	CompanyLogo sql.NullString `json:"company_logo"`
	UserID      string         `json:"user_id"`
}

type CompanyUser struct {
	UserID    string `json:"user_id"`
	CompanyID string `json:"company_id"`
}

type Idea struct {
	IdeaID          string       `json:"idea_id"`
	IdeaTitle       string       `json:"idea_title"`
	IdeaDescription string       `json:"idea_description"`
	IdeaAuthor      string       `json:"idea_author"`
	IdeaCreatedAt   sql.NullTime `json:"idea_created_at"`
	IdeaUpdatedAt   sql.NullTime `json:"idea_updated_at"`
	IdeaDeletedAt   sql.NullTime `json:"idea_deleted_at"`
	CompanyID       string       `json:"company_id"`
}

type Otp struct {
	Otp      string       `json:"otp"`
	Email    string       `json:"email"`
	Expiry   time.Time    `json:"expiry"`
	Verified sql.NullBool `json:"verified"`
}

type User struct {
	UserID        string         `json:"user_id"`
	FullName      sql.NullString `json:"full_name"`
	Email         string         `json:"email"`
	EmailVerified bool           `json:"email_verified"`
	Picture       string         `json:"picture"`
	UserPassword  string         `json:"user_password"`
	UserCreatedAt time.Time      `json:"user_created_at"`
	UserLastLogin time.Time      `json:"user_last_login"`
}
