// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	AddNewUser(ctx context.Context, arg AddNewUserParams) (User, error)
	EmailExistsInDB(ctx context.Context, email string) (bool, error)
}

var _ Querier = (*Queries)(nil)
